pipeline {
    options {
        disableConcurrentBuilds()
    }
    agent {
        docker {
                label 'haim-cloud-governance-worker'
                image 'quay.io/athiru/centos-stream8-podman:latest'
                args  '--net="host" -u root -v /etc/postfix/main.cf:/etc/postfix/main.cf --privileged'
        }
    }
    environment {
        HAIM_CREDS = credentials('haim-creds')
        AWS_SECRET_ACCESS_KEY_APPENG = credentials('appeng-aws-secret-key-id')
        BUCKET_APPENG = credentials('appeng-s3-bucket')
        AWS_IAM_USER_SPREADSHEET_ID = credentials('cloud-governance-aws-iam-user-spreadsheet-id')
        GOOGLE_APPLICATION_CREDENTIALS = credentials('cloud-governance-google-application-credentials')
        LDAP_HOST_NAME = credentials('redhat-ldap-hostname')
        ES_HOST = credentials('haim-cloud-governance-elasticsearch-url')
        ES_PORT = credentials('haim-cloud-governance-elasticsearch-port')
        SPREADSHEET_ID = credentials('cloud-governance-aws-iam-user-spreadsheet-id')

        contact2 = "athiruma@redhat.com"
    }
    stages {
        stage('Checkout') { // Checkout (git clone ...) the projects repository
           steps {
                 checkout scm
           }
        }
        stage('Initial Cleanup') {
            steps {
                 sh '''if [[ "$(podman images -q quay.io/ebattat/cloud-governance 2> /dev/null)" != "" ]]; then podman rmi -f $(podman images -q quay.io/ebattat/cloud-governance 2> /dev/null); fi'''
            }
        }
        stage('Run Policies for haim poc') {
            steps {
                 sh 'python3 jenkins/poc/haim/daily/run_policies.py'
            }
        }
        stage('Upload Policies output to ElasticSearch for haim poc') {
            steps {
                 sh 'python3 jenkins/poc/haim/daily/es_upload.py'
            }
        }
        stage('Finalize Cleanup') {
            steps {
                 sh '''if [[ "$(podman images -q quay.io/ebattat/cloud-governance 2> /dev/null)" != "" ]]; then podman rmi -f $(podman images -q quay.io/ebattat/cloud-governance 2> /dev/null); fi'''
                 deleteDir()
            }
        }
    }
    post {
        failure {
              script {
                msg = "Build error for ${env.JOB_NAME} ${env.BUILD_NUMBER} (${env.BUILD_URL})"
                emailext body: """\
            Jenkins job: ${env.BUILD_URL}\nSee the console output for more details:  ${env.BUILD_URL}consoleFull\n\n
            """,subject: msg, to: "${contact2}, ${contact2}, ${contact2}"
            }
          }
    }
}
