apiVersion: v1
kind: Pod
metadata:
  name: cloud-governance-pod
spec:
  containers:
    - name: elasticsearch
      image: docker.elastic.co/elasticsearch/elasticsearch:8.8.0
      ports:
        - containerPort: 9200
          hostPort: 9200
      env:
        - name: discovery.type
          value: "single-node"
        - name: xpack.security.enabled
          value: "false"
      volumeMounts:
        - mountPath: /usr/share/elasticsearch/data
          name: elasticsearch-data
    - name: kibana
      image: docker.elastic.co/kibana/kibana:8.8.0
      ports:
        - containerPort: 5601
          hostPort: 5601
      env:
        - name: ELASTICSEARCH_HOSTS
          value: http://localhost:9200
    - name: grafana
      image: docker.io/grafana/grafana:8.2.0
      ports:
        - containerPort: 3000
          hostPort: 3000
      volumeMounts:
        - mountPath: /var/lib/grafana
          name: grafana-data
  volumes:
    - name: elasticsearch-data
      hostPath:
        path: $CLOUD_GOVERNANCE_PATH/elasticsearch
        type: DirectoryOrCreate
    - name: grafana-data
      hostPath:
        path: $CLOUD_GOVERNANCE_PATH/grafana
        type: DirectoryOrCreate

# replace CLOUD_GOVERNANCE_PATH with directory_name
